### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ModeenF**
Se my changes, some things I was finding annoying. More can come as I'm moving from Momentics to VS. I don't know if the first one are anything to have but the CS one I beleve are :)

### CODE REVIEW

**Comment by phofman** [comment]
Sorry, but I can't accept your submission, because:
1) I haven't seen you on [that](http://blackberry.github.io/approvedSignatories.html) list, see [wiki](/phofman/vs-plugin/wiki/Contribution) for details

2) the main plugin DLL must depend on the native tool, which you removed, as otherwise it won't be placed inside the final VSIX at expected location

But the good news is that I can implement the feature you wish about editing simulator password and create the release myself ;) If you have more ideas, please submit them via [Issues tab](/phofman/vs-plugin/issues) or sign required CLA.

Thanks

**Comment by ModeenF** [comment]
```
                                                                                  Sorry missed thos things. NpAnother thing. I don't Have coloring or intelisens on qml are that suppose to work?Can nr 2 be the reason it don't work? Other things works :)                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10-smartphone                                                                                                                                                                                                                Från: Paweł HofmanSkickat: onsdagen den 18:e november 2015 17:03Till: phofman/vs-pluginSvara till: phofman/vs-pluginKopia: ModeenFÄmne: Re: [vs-plugin] Develop (#54)Sorry, but I can't accept your submission, because:
```

1) I haven't seen you on that list, see wiki for details

2) the main plugin DLL must depend on the native tool, which you removed, as otherwise it won't be placed inside the final VSIX at expected location

But the good news is that I can implement the feature you wish about editing simulator password and create the release myself ;) If you have more ideas, please submit them via Issues tab or sign required CLA.

Thanks

—Reply to this email directly or view it on GitHub.

**Comment by phofman** [comment]
Hi,

No problem. Missing the 'GBD.Host' executable could only affect debugger integration. It's some kind of bridge between plugin and the BlackBerry/QNX GDB from NDK.

It has no influence on QML coloring nor IntelliSense. Coloring should work, maybe I screw something around clearing font caches (feel free to fire a bug for that). Try resetting your Visual Studio settings via (Tools -> Import and Export Settings... -> Reset All Settings...) or just delete "HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\**&lt;version&gt;**\FontAndColors\Cache". And IntelliSense integration is not implemented at all, maybe this is the reason you don't see it working ;). I know, it's a nice-to-have feature, but won't be there in the near future still. Sorry.

Cheers.

**Comment by ModeenF** [comment]
```
                                                                                  Thanks. I wasn't sure if I made some thing wrong. I will test.                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10-smartphone                                                                                                                                                                                                                Från: Paweł HofmanSkickat: fredagen den 20:e november 2015 00:15Till: phofman/vs-pluginSvara till: phofman/vs-pluginKopia: ModeenFÄmne: Re: [vs-plugin] Develop (#54)Hi,
```

No problem. Missing the 'GBD.Host' executable could only affect debugger integration. It's some kind of bridge between plugin and the BlackBerry/QNX GDB from NDK.

It has no influence on QML coloring nor IntelliSense. Coloring should work, maybe I screw something around clearing font caches (feel free to fire a bug for that). Try resetting your Visual Studio settings via (Tools -> Import and Export Settings... -> Reset All Settings...) or just delete "HKEY_CURRENT_USER\Software\Microsoft\VisualStudio<version>\FontAndColors\Cache". And IntelliSense integration is not implemented at all, maybe this is the reason you don't see it working ;). I know, it's a nice-to-have feature, but won't be there in the near future still. Sorry.

Cheers.

—Reply to this email directly or view it on GitHub.

**Comment by ModeenF** [comment]
Re setting didn't help. Removing reg key did :) 

Have we any code from QT vs project? I have downloaded it now to see
have they have done things. 

Hm I'm at the WIKI now and it look's like a pain to contribute code (not
code and application vise) but in sending document back and fourth.. I'
am in Sweden and sending document to Canada would probably cost money..
not much but "just code" disappeared :) 

If it's ok with you and if I get anything useful done perhaps you can
sherry pick it from me? I will tell you when I/if I have anything so you
don't need to whats my changes all the time :) 

2015-11-20 00:06 skrev Paweł Hofman: 

> Hi, 
> 
> No problem. Missing the 'GBD.Host' executable could only affect debugger integration. It's some kind of bridge between plugin and the BlackBerry/QNX GDB from NDK. 
> 
> It has no influence on QML coloring nor IntelliSense. Coloring should work, maybe I screw something around clearing font caches (feel free to fire a bug for that). Try resetting your Visual Studio settings via (Tools -> Import and Export Settings... -> Reset All Settings...) or just delete "HKEY_CURRENT_USER\Software\Microsoft\VisualStudio<VERSION>\FontAndColors\Cache". And IntelliSense integration is not implemented at all, maybe this is the reason you don't see it working ;). I know, it's a nice-to-have feature, but won't be there in the near future still. Sorry. 
> 
> Cheers. 
> 
> ## 
> 
> Reply to this email directly or view it on GitHub [1].

## Links:

[1] https://github.com/phofman/vs-plugin/pull/54#issuecomment-158228661

**Comment by phofman** [comment]
Hi there!

There is no code from Qt in this project. Beside that, I don't know, why you could actually need it. After all this is all about Visual Studio and BlackBerry NDK. It could be much more helpful to reach people from Momentics team and ask for sharing their knowledge and metadata, but I failed doing that.

At the end, I am from Poland, not Canada.

Final thought - if you want to continue, could we take this discussion off-line? My email is on my profile page. It is not related at all to this pull-request.

**Pull request closed without merging**
